services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod

    # Laravel project will live here
    working_dir: /var/www

    env_file:
      - ./backend/.env.prod

    volumes:
      - ./backend/.env.prod:/var/www/.env
      - public_data:/var/www/public

    depends_on:
      - db

    command: /entrypoint.sh

    networks:
      - laravel

    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    environment:
      APP_ROOT: /var/www

    # Publish container port 80 to localhost:8040 on the server
    ports:
      - '127.0.0.1:8040:80'

    # Give nginx access to project files Prefer container
    volumes:
      - public_data:/var/www/public
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template

    depends_on:
      - app

    networks:
      - laravel

    restart: unless-stopped

  db:
    image: docker.io/library/mysql:8.0

    # Load MySQL credentials from .env file
    env_file:
      - ./backend/.env.prod

    # Use native password plugin for compatibility with Laravel's MySQL driver
    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - dbdata:/var/lib/mysql

    networks:
      - laravel

    restart: unless-stopped

# Used for persistent MySQL data, managed by Docker
volumes:
  dbdata:
  public_data:

# Internal Docker network for container communication
networks:
  laravel:
