name: Deploy to Production

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'todo.txt'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy through relay server
        uses: appleboy/ssh-action@v0.1.7

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            set -e

            ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.TWEBAN_KEY }} -p ${{ secrets.TWEBAN_PORT }} ${{ secrets.TWEBAN_USER }}@${{ secrets.TWEBAN_HOST }} "
              cd ${{ secrets.TWEBAN_PATH }} &&
              echo '${{ secrets.ENV_PROD_CONTENT }}' > .env &&
              ./deploy.sh
            "
